### ISSUE TITLE
Full screen mode doesn't show Thumbnails

### ISSUE THREAD

**Issue by adamjarling** [samvera-labs/openseadragon-react-viewer#11]
### Description
For some reason when in full screen mode, the viewer doesn't display thumbnail selectors.  The toolbar continues to display though, allowing the user to come out full screen mode and see the viewer again.

### Done looks like
- Full screen mode shows the viewer as expected.

**Comment by katdivyareddy10** [comment]
@adamjarling This is not a bug but a feature in OSD viewer where all the components except `Toolbar` are hidden on `full-page` mode. Please refer to [OpenSeadragon viewer code](https://openseadragon.github.io/docs/openseadragon.js.html#line8150) from the docs for the same.
