### ISSUE TITLE
how to use DZI

### ISSUE THREAD

**Issue by firstdorsal** [samvera-labs/openseadragon-react-viewer#59]
hi,
i want to get deep zoom images to work:
https://openseadragon.github.io/examples/tilesource-dzi/
but your project needs to load a manifest.
i cant get the native openseadragon project to work with react.
is it possible to use dzi with your viewer?

**Comment by adamjarling** [comment]
Hi @firstdorsal I'll see if we can support individual tile sources in this package.   The original use case was pull in metadata from a IIIF manifest alongside images.     

You may be interested in this package, which could support your use case directly:

https://github.com/stephenwf/use-open-seadragon
